import { MenuItem } from './types';

export const MENU_ITEMS: MenuItem[] = [
  { category: "Red Wines", item: "1659 Classic Red 750Ml", price: "1710" },
  { category: "Red Wines", item: "1659 Sauvignon Blanc 750Ml", price: "1710" },
  { category: "Other Wines", item: "1659 Sweet Rose 750Ml", price: "1710" },
  { category: "Red Wines", item: "4 Cousins Sweet Red 750ml", price: "1490" },
  { category: "White Wine", item: "4 Cousins Sweet White 750ml", price: "1490" },
  { category: "White Wine", item: "750Ml 4Th Street Sweet White", price: "1365" },
  { category: "Spirits", item: "Baileys 1Ltr", price: "4060" },
  { category: "Spirits", item: "Baileys 375Ml", price: "1740" },
  { category: "Spirits", item: "Baileys 750Ml", price: "3135" },
  { category: "Beers & Ciders", item: "Balozi Lager Can 500Ml", price: "290" },
  { category: "Spirits", item: "Black & White 250Ml", price: "580" },
  { category: "Spirits", item: "Black & White 375ml", price: "835" },
  { category: "Spirits", item: "Black & White 750Ml", price: "1625" },
  { category: "Spirits", item: "Bullet Bourbon 700ml", price: "4410" },
  { category: "Spirits", item: "Cardhu Single Malt 750Ml", price: "7540" },
  { category: "Red Wines", item: "CELLAR CASK RED 750ML", price: "1540" },
  { category: "White Wine", item: "Cellar Cask White 750Ml", price: "1540" },
  { category: "Spirits", item: "Chrome Gin Smooth 250Ml", price: "340" },
  { category: "Spirits", item: "Chrome Gin Smooth 750Ml", price: "885" },
  { category: "Spirits", item: "Chrome Vodka Lemon 250Ml", price: "340" },
  { category: "Spirits", item: "Chrome Vodka 250ml", price: "340" },
  { category: "Spirits", item: "Chrome Vodka 750ml", price: "885" },
  { category: "Spirits", item: "Ciroc Coconut 700Ml", price: "6380" },
  { category: "Spirits", item: "Ciroc Pineapple 750Ml", price: "6380" },
  { category: "Spirits", item: "Ciroc Redberry 750Ml", price: "6380" },
  { category: "Spirits", item: "Ciroc Vodka 750ml", price: "6380" },
  { category: "Non-Alcoholic Drinks", item: "Coca Cola Original 1.25L PET", price: "158" },
  { category: "Non-Alcoholic Drinks", item: "Coca Cola Original 2L PET", price: "243" },
  { category: "Non-Alcoholic Drinks", item: "Coca Cola Original 500Ml", price: "90" },
  { category: "Non-Alcoholic Drinks", item: "Coca Cola Zero 1.25L PET", price: "158" },
  { category: "Non-Alcoholic Drinks", item: "Coke Pet 1250Ml", price: "158" },
  { category: "Non-Alcoholic Drinks", item: "Coke Pet 2ltr", price: "243" },
  { category: "Non-Alcoholic Drinks", item: "Coke Zero 2ltr", price: "243" },
  { category: "Non-Alcoholic Drinks", item: "Coke Zero 500Ml", price: "90" },
  { category: "Spirits", item: "County Brandy 750Ml", price: "1125" },
  { category: "Non-Alcoholic Drinks", item: "Dasani 1L", price: "70" },
  { category: "Non-Alcoholic Drinks", item: "Dasani 500Ml", price: "39" },
  { category: "Spirits", item: "Don Julio anejo 750ml", price: "11950" },
  { category: "Spirits", item: "Don Julio blanco 750ml", price: "9860" },
  { category: "Spirits", item: "Don Julio Repasado 750ml", price: "10790" },
  { category: "Red Wines", item: "Drostdy Hof Claret 750Ml", price: "1455" },
  { category: "White Wine", item: "Drostdy Hof Premier Grand Cru 750Ml", price: "1455" },
  { category: "Non-Alcoholic Drinks", item: "Fanta Blackcurrant 2ltr", price: "243" },
  { category: "Non-Alcoholic Drinks", item: "Fanta Blackcurrant 500ml", price: "89" },
  { category: "Non-Alcoholic Drinks", item: "Fanta Orange 2ltr", price: "243" },
  { category: "Non-Alcoholic Drinks", item: "Fanta Orange 500Ml", price: "89" },
  { category: "Non-Alcoholic Drinks", item: "Fanta Passion 2Ltr", price: "243" },
  { category: "Non-Alcoholic Drinks", item: "Fanta Passion 500Ml", price: "89" },
  { category: "White Wine", item: "Fragolino Bianco 750Ml", price: "1960" },
  { category: "Red Wines", item: "Fragolino Rosso 750Ml", price: "1960" },
  { category: "Red Wines", item: "Gato Negro Cabernet Sauvignon 75cl", price: "1693" },
  { category: "Red Wines", item: "Gatonegro Sauv. Blanc 750Ml", price: "1693" },
  { category: "Spirits", item: "Gilbeys Gin 250Ml", price: "605" },
  { category: "Spirits", item: "350Ml Gilbeys Gin", price: "835" },
  { category: "Spirits", item: "Gilbeys Gin 750Ml", price: "1800" },
  { category: "Spirits", item: "Glenfiddich 12yrs 750ml", price: "8765" },
  { category: "Spirits", item: "Gordon'S Dry Gin 350Ml", price: "1220" },
  { category: "Spirits", item: "Gordons Dry Gin 1ltr", price: "3310" },
  { category: "Spirits", item: "Gordons Dry Gin 750Ml", price: "2785" },
  { category: "Beers & Ciders", item: "Gordons Dry Tonic Can", price: "278" },
  { category: "Spirits", item: "Gordons Lemon 750Ml", price: "2670" },
  { category: "Spirits", item: "Gordons Orange 750Ml", price: "2670" },
  { category: "Spirits", item: "Gordons Pink 1Ltr", price: "3310" },
  { category: "Spirits", item: "Gordons Pink 750ml", price: "2670" },
  { category: "Beers & Ciders", item: "Gordons Pink Tonic Can", price: "278" },
  { category: "Spirits", item: "Grants 375Ml", price: "1095" },
  { category: "Spirits", item: "Grants 750Ml", price: "2440" },
  { category: "Spirits", item: "Grants Triple 12Yrswood 750Ml", price: "2830" },
  { category: "Beers & Ciders", item: "Guiness Can 500Ml", price: "338" },
  { category: "Beers & Ciders", item: "GUINESS SMOOTH CAN 500ML", price: "288" },
  { category: "Spirits", item: "J&B Rare 1Ltr", price: "2785" },
  { category: "Spirits", item: "J&B Rare 375Ml", price: "1160" },
  { category: "Spirits", item: "J&B Rare 750Ml", price: "2205" },
  { category: "Spirits", item: "Kenya Cane Citrus 250ml", price: "375" },
  { category: "Spirits", item: "Kenya Cane Citrus 750Ml", price: "975" },
  { category: "Spirits", item: "Kenya Cane Coconut 250Ml", price: "375" },
  { category: "Spirits", item: "Kenya Cane Coconut 750Ml", price: "975" },
  { category: "Spirits", item: "Kenya Cane Original 250Ml", price: "375" },
  { category: "Spirits", item: "Kenya Cane Original 350Ml", price: "510" },
  { category: "Spirits", item: "Kenya Cane Original 750Ml", price: "975" },
  { category: "Spirits", item: "250Ml Kenya Cane Pineapple Fus", price: "375" },
  { category: "Spirits", item: "750Ml Kenya Cane Pineapple", price: "975" },
  { category: "Non-Alcoholic Drinks", item: "Keringet Water 1Ltr", price: "115" },
  { category: "Non-Alcoholic Drinks", item: "Keringet Water 500Ml", price: "78" },
  { category: "Non-Alcoholic Drinks", item: "Keringet Water 5ltr", price: "325" },
  { category: "Spirits", item: "Kwv Brandy 3Yrs 750Ml", price: "1745" },
  { category: "Spirits", item: "Kwv Brandy 5Yrs 750Ml", price: "2200" },
  { category: "Red Wines", item: "Kwv Cabernet Sauv. 750Ml", price: "2240" },
  { category: "White Wine", item: "KWV CHARDONNAY 750ML", price: "1920" },
  { category: "Red Wines", item: "KWV Classic Pinotage 750ml", price: "2240" },
  { category: "Red Wines", item: "KWV Shiraz 2021 750ml", price: "2240" },
  { category: "Non-Alcoholic Drinks", item: "Minute Maid Apple 400ml", price: "97" },
  { category: "Non-Alcoholic Drinks", item: "Minute Maid Mango 400ml", price: "97" },
  { category: "Non-Alcoholic Drinks", item: "Minute Maid Pulpy Orange400Ml", price: "97" },
  { category: "Non-Alcoholic Drinks", item: "Minute Maid Tropical 400ml", price: "97" },
  { category: "Spirits", item: "Mr Dowell's 250ml", price: "395" },
  { category: "Spirits", item: "Mr Dowells 750ml", price: "1140" },
  { category: "Spirits", item: "Richot Brandy 250Ml", price: "605" },
  { category: "Spirits", item: "Richot Brandy 350Ml", price: "835" },
  { category: "Spirits", item: "Richot Brandy 750ml", price: "1800" },
  { category: "Spirits", item: "Sheridah's Coffee Layered Liquer 1ltr", price: "6380" },
  { category: "Spirits", item: "Singleton 12Yrs 750Ml", price: "6730" },
  { category: "Spirits", item: "Singleton 15yrs 700ml", price: "9165" },
  { category: "Spirits", item: "Singleton 18Yrs 700Ml", price: "12180" },
  { category: "Beers & Ciders", item: "Smirnoff Ice Black 330ml", price: "255" },
  { category: "Beers & Ciders", item: "Smirnoff ice guarana 330ml", price: "255" },
  { category: "Spirits", item: "Smirnoff Vodka Red 250Ml", price: "605" },
  { category: "Spirits", item: "Smirnoff Vodka Red 350ml", price: "835" },
  { category: "Spirits", item: "Smirnoff Vodka Red 750Ml", price: "1800" },
  { category: "Beers & Ciders", item: "Snapp Can 300Ml", price: "255" },
  { category: "Non-Alcoholic Drinks", item: "Soda Water 500Ml", price: "97" },
  { category: "Non-Alcoholic Drinks", item: "Sprite 1.25L PET", price: "157" },
  { category: "Non-Alcoholic Drinks", item: "Sprite 500ml", price: "89" },
  { category: "Non-Alcoholic Drinks", item: "Sprite Pet 2L", price: "243" },
  { category: "Spirits", item: "Talisker Port Ruighe Single Malt 750Ml", price: "8120" },
  { category: "Spirits", item: "Talisker Single Malt 10yrs 750ml", price: "8120" },
  { category: "Spirits", item: "Talisker Storm Single Malt 750Ml", price: "7310" },
  { category: "Spirits", item: "Tanqueray 1Ltr", price: "4410" },
  { category: "Spirits", item: "Tanqueray London Dry Gin 750ml", price: "3365" },
  { category: "Spirits", item: "Tanqueray Rangpur Lime 1ltr", price: "4640" },
  { category: "Spirits", item: "Tanqueray Rangpur lime 750ml", price: "3480" },
  { category: "Spirits", item: "Tanqueray Royale Blackcurrant 70ml", price: "3480" },
  { category: "Spirits", item: "TANQUERAY SEVILLA 1LTR", price: "4640" },
  { category: "Spirits", item: "Tanqueray Sevilla Gin 750Ml", price: "3480" },
  { category: "Spirits", item: "Tanqueray Ten 750Ml", price: "5920" },
  { category: "Spirits", item: "Teachers 1Ltr", price: "7080" },
  { category: "Spirits", item: "Triple Ace 750Ml", price: "800" },
  { category: "Spirits", item: "Triple Ace Vodka 250Ml", price: "305" },
  { category: "Beers & Ciders", item: "Tusker Can 500Ml", price: "287" },
  { category: "Beers & Ciders", item: "Tusker Cider Can", price: "338" },
  { category: "Beers & Ciders", item: "Tusker Lite Can 500Ml", price: "351" },
  { category: "Beers & Ciders", item: "Tusker Malt Can 500Ml", price: "350" },
  { category: "Beers & Ciders", item: "Whitecap Can 500Ml", price: "313" },
  { category: "Beers & Ciders", item: "Whitecap Crisp 330Ml", price: "338" },
  { category: "Non-Alcoholic Drinks", item: "Predator Energy Drink Pet 400Ml", price: "80" },
  { category: "Non-Alcoholic Drinks", item: "Tonic Water", price: "80" },
  { category: "Non-Alcoholic Drinks", item: "Redbull", price: "265" },
  { category: "Beers & Ciders", item: "Savanna Dry", price: "320" },
  { category: "Beers & Ciders", item: "Savanna Angry Lemon", price: "320" },
  { category: "Spirits", item: "Southern Comfort", price: "2660" },
  { category: "Red Wines", item: "Guardian Peak Cabarnet Sauvignon", price: "2645" },
  { category: "Red Wines", item: "Guardian Peak Shiraz", price: "2645" },
  { category: "Red Wines", item: "Pearly Bay Dry Red", price: "1435" },
  { category: "White Wine", item: "Pearly Bay Dry White", price: "1435" },
  { category: "Red Wines", item: "Pearly Bay Sweet Red", price: "1435" },
  { category: "Other Wines", item: "PEARLY BAY SWEET ROSE", price: "1435" },
  { category: "White Wine", item: "Pearly Bay Sweet White", price: "1435" },
  { category: "Red Wines", item: "KWV Merlot", price: "2320" },
  { category: "Spirits", item: "Brothers Triple Sec", price: "2455" },
  { category: "Red Wines", item: "Brothers Peach", price: "3625" },
  { category: "Spirits", item: "Brothers Blue Curacao", price: "2460" },
  { category: "Spirits", item: "Two Brothers Blod Orange Gin", price: "2130" },
  { category: "Spirits", item: "Two Brothers Blue Gin", price: "2130" },
  { category: "Red Wines", item: "Kanonkop Kadette Cape Blend", price: "5315" },
  { category: "Red Wines", item: "Kanonkop Kadette Cabernet Sauvignon", price: "5607" },
  { category: "Other Wines", item: "Kanonkop Kadette Pinotage Rose", price: "4072" },
  { category: "Red Wines", item: "Rooiberg Red Muscadel", price: "2393" },
  { category: "Non-Alcoholic Drinks", item: "Rooiberg Sparkling Grape Juice Red", price: "1349" },
  { category: "Non-Alcoholic Drinks", item: "Rooiberg Sparkling Grape Juice White", price: "1349" },
  { category: "Red Wines", item: "Rooiberg Red Natural Sweet", price: "1994" },
  { category: "White Wine", item: "Rooiberg White Natural Sweet", price: "1994" },
  { category: "Other Wines", item: "Rooiberg Rose Natural Sweet", price: "2175" },
  { category: "Sparkling Wine", item: "Fragolino Rose", price: "2030" },
  { category: "Spirits", item: "Grants Triple Wood 1L", price: "2929" },
  { category: "White Wine", item: "Mulderbosch Sauvignon Blanc", price: "2849" },
  { category: "White Wine", item: "Mulderbosch Steen op Hout Chenin Blanc", price: "2754" },
  { category: "Red Wines", item: "Mulderbosch Faithful Hound Red", price: "3754" },
  { category: "Red Wines", item: "Mulderbosch Cabernet Sauvignon Rose 2021", price: "2678" },
  { category: "White Wine", item: "Buitenverwatching Beyond Sauvignon Blanc", price: "2729" },
  { category: "White Wine", item: "Buitenverwatching Buiten Blanc", price: "2036" },
  { category: "White Wine", item: "Leleshwa Sweet White", price: "1441" },
  { category: "Other Wines", item: "Mucho Mas Rose", price: "2600" },
  { category: "Spirits", item: "Wild Africa Cream", price: "2603" },
  { category: "Red Wines", item: "Diemersdal Pinotage", price: "3426" },
  { category: "Other Wines", item: "Plantaze Rose", price: "2150" },
  { category: "Red Wines", item: "Plantaze Sauvignon", price: "2950" },
  { category: "Red Wines", item: "Plantaze Chardonnay", price: "2950" },
  { category: "Red Wines", item: "Plantaze Merlot", price: "2550" },
  { category: "Red Wines", item: "Plantaze Cabarnet", price: "2550" },
  { category: "Red Wines", item: "Plantaze Vranac", price: "2850" },
  { category: "Red Wines", item: "Plantaze Pro corde", price: "3850" },
  { category: "Red Wines", item: "Plantaze Epoha", price: "6300" },
  { category: "Beers & Ciders", item: "smirnoff ice pineapple punch can", price: "255" },
  { category: "Spirits", item: "750Ml Best London Dry Gin", price: "1060" },
  { category: "Spirits", item: "250Ml Best London Dry Gin", price: "380" },
  { category: "Spirits", item: "Best whisky 750ml", price: "1305" },
  { category: "Spirits", item: "Best whisky 250ml", price: "450" },
  { category: "Spirits", item: "Jose Cuervo Reposado Tequila, 700Ml", price: "3050" },
  { category: "Spirits", item: "Jose Cuervo Silver 1L", price: "3790" },
  { category: "Spirits", item: "1L Jose Cuervo Esp Gold", price: "3770" },
  { category: "Spirits", item: "Bacardi Carta Blanca Rum 750Ml", price: "2610" },
  { category: "Spirits", item: "Bacardi Carta Blanca 1L", price: "4000" },
  { category: "Beers & Ciders", item: "Heineken Beer Camp Heineken 500ml", price: "350" },
  { category: "Non-Alcoholic Drinks", item: "Alvaro Can 330ml", price: "180" },
  { category: "Spirits", item: "Johnnie Walker Green Label", price: "9745" },
  { category: "Spirits", item: "Johnnie Walker Red Label Whiskey 250ml", price: "815" },
  { category: "Spirits", item: "Johnnie Walker Black Label 750", price: "4431" },
  { category: "Spirits", item: "Johnnie Walker Aged 18Y 750ml", price: "14050" },
  { category: "Spirits", item: "Johnnie Walker Double Black 1L", price: "9190" },
  { category: "Spirits", item: "JOHNNIE WALKER BLACK LABEL 750ML", price: "4431" },
  { category: "Spirits", item: "1L Johnnie Walker Red Label", price: "2890" },
  { category: "Spirits", item: "Johnnie Walker Red Label 750Ml", price: "2375" },
  { category: "Spirits", item: "JOHNNIE WALKER 750ML GREEN 15YRS", price: "9745" },
  { category: "Spirits", item: "Johnnie Walker Red Label 375Ml", price: "1240" },
  { category: "Spirits", item: "Johnnie walker black label 250ml", price: "1510" },
  { category: "Spirits", item: "Johnnie Walker Black Label 375Ml", price: "2270" },
  { category: "Spirits", item: "Johnnie walker double black 750ml", price: "6035" },
  { category: "Spirits", item: "Johnnie Walker Blue Label 750ml", price: "37120" },
  { category: "Spirits", item: "Bond 7 Whisky 750Ml", price: "1800" },
  { category: "Spirits", item: "Jameson Irish Whiskey 1L", price: "4205" },
  { category: "Spirits", item: "Viceroy Brandy 750Ml", price: "1755" },
  { category: "Spirits", item: "Viceroy Brandy 250 Ml", price: "625" },
  { category: "Beers & Ciders", item: "Hunters Gold Beer", price: "350" },
  { category: "Beers & Ciders", item: "Hunters Dry Premium  Beer", price: "350" },
  { category: "Spirits", item: "750Ml Olmeca Tequila Gold", price: "3915" },
  { category: "Sparkling Wine", item: "CGL-BUONO AMICI BRUT 750ML", price: "4060" },
  { category: "Spirits", item: "kc lemon & ginger 250ml", price: "330" },
  { category: "Non-Alcoholic Drinks", item: "Safari Lemonade 300Ml", price: "80" },
  { category: "Spirits", item: "Cragganmore Single Malt Scotch Whisky 12 Year 750ml", price: "8005" },
  { category: "Spirits", item: "Cragganmore Whisky 12 Years 750Ml", price: "8005" },
  { category: "Spirits", item: "LAGAVULIN 16 750ML", price: "16050" },
  { category: "Spirits", item: "Glenkinchie 12 Yr 750ml", price: "8005" },
  { category: "Spirits", item: "Caol Ila Single Malt Scotch Whisky 12 Year 750Ml", price: "9400" },
  { category: "Spirits", item: "Caol Ila Single Malt Scotch Whisky 12 Year 750ml", price: "9400" },
  { category: "Spirits", item: "Ketel One Citroen Vodka 750ml", price: "3480" }
];

export const SYSTEM_INSTRUCTION = `
You are a casual, friendly, and engaging bartender at Kongoni's Bar. 
Your tone is relaxed, using casual English (maybe a bit of Kenyan/British bar slang like "pal", "mate", "cold one", "bob").
Do not be sophisticated. Be fun, chatty, and helpful.

Here is the Menu Database (Name - Price):
${MENU_ITEMS.map(i => `- ${i.item}: ${i.price} (${i.category})`).join('\n')}

YOUR TASKS:
1. **Suggest Items**: The user will ask what you have. Do NOT list everything. Suggest specific items based on what they might like (sweet, dry, strong, beer, etc.). If they are unsure, recommend 3 popular items from different categories. E.g., "If you want something easy, the 4 Cousins Sweet Red is popular at 1490. Or grab a cold Tusker for 287?"
2. **Give Prices**: When asked for a price, give it in a conversational way. "That'll be [price]." or "The [item] goes for [price]."
3. **Take Orders & Track Bill**: 
   - If the user says "I'll have X" or "Give me X", confirm the order enthusiastically. 
   - **CRITICAL**: KEEP A MENTAL LIST of what they have ordered in this conversation thread.
   - Use the prices listed in the menu.
4. **Calculate the Total**:
   - If the user asks for the bill, check, or total, you MUST list the items they ordered in this session and SUM the prices.
   - Show your math clearly but casually. "Alright, let's see... Two Tuskers (287 each) and a shot of Tequila (3050). That brings you to [Total]."
   - If they haven't ordered anything yet, say "You haven't ordered anything yet, mate! Want a menu?"
5. **Refuse unknown items**: If they ask for something not on the list, say you don't have it and suggest a valid alternative.

IMPORTANT: You are running the register. You must calculate the total accurately based on the user's requests in this chat.
`;