import { MenuItem } from './types';

export const MENU_ITEMS: MenuItem[] = [
  // Red Wines
  { category: "Red Wines", item: "1659 Classic Red 750Ml", price: "1710", description: "Classic choice" },
  { category: "Red Wines", item: "1659 Sauvignon Blanc 750Ml", price: "1710", description: "Smooth finish" },
  { category: "Red Wines", item: "4 Cousins Sweet Red 750ml", price: "1490", description: "Sweet and popular" },
  { category: "Red Wines", item: "CELLAR CASK RED 750ML", price: "1540", description: "Solid table wine" },
  { category: "Red Wines", item: "Drostdy Hof Claret 750Ml", price: "1455", description: "Dry red blend" },
  { category: "Red Wines", item: "Fragolino Rosso 750Ml", price: "1960", description: "Sparkling strawberry notes" },
  { category: "Red Wines", item: "Gato Negro Cabernet Sauvignon 75cl", price: "1693", description: "Bold Cabernet" },
  { category: "Red Wines", item: "Gatonegro Sauv. Blanc 750Ml", price: "1693", description: "Crisp Sauvignon" },
  { category: "Red Wines", item: "Kwv Cabernet Sauv. 750Ml", price: "2240", description: "Full bodied" },
  { category: "Red Wines", item: "KWV Classic Pinotage 750ml", price: "2240", description: "Classic SA Pinotage" },
  { category: "Red Wines", item: "KWV Shiraz 2021 750ml", price: "2240", description: "Spicy notes" },
  { category: "Red Wines", item: "Guardian Peak Cabarnet Sauvignon", price: "2645", description: "Premium selection" },
  { category: "Red Wines", item: "Guardian Peak Shiraz", price: "2645", description: "Rich shiraz" },
  { category: "Red Wines", item: "Pearly Bay Dry Red", price: "1435", description: "Easy drinking" },
  { category: "Red Wines", item: "Pearly Bay Sweet Red", price: "1435", description: "Sweet finish" },
  { category: "Red Wines", item: "KWV Merlot", price: "2320", description: "Smooth Merlot" },
  { category: "Red Wines", item: "Brothers Peach", price: "3625", description: "Fruity infusion" },
  { category: "Red Wines", item: "Kanonkop Kadette Cape Blend", price: "5315", description: "Complex blend" },
  { category: "Red Wines", item: "Kanonkop Kadette Cabernet Sauvignon", price: "5607", description: "Top shelf Cab" },
  { category: "Red Wines", item: "Rooiberg Red Muscadel", price: "2393", description: "Dessert style" },
  { category: "Red Wines", item: "Rooiberg Red Natural Sweet", price: "1994", description: "Naturally sweet" },
  { category: "Red Wines", item: "Mulderbosch Faithful Hound Red", price: "3754", description: "Elegant blend" },
  { category: "Red Wines", item: "Mulderbosch Cabernet Sauvignon Rose 2021", price: "2678", description: "Refreshing Rose" },
  { category: "Red Wines", item: "Diemersdal Pinotage", price: "3426", description: "Coffee chocolate notes" },
  { category: "Red Wines", item: "Plantaze Sauvignon", price: "2950", description: "Imported quality" },
  { category: "Red Wines", item: "Plantaze Chardonnay", price: "2950", description: "Imported quality" },
  { category: "Red Wines", item: "Plantaze Merlot", price: "2550", description: "Imported quality" },
  { category: "Red Wines", item: "Plantaze Cabarnet", price: "2550", description: "Imported quality" },
  { category: "Red Wines", item: "Plantaze Vranac", price: "2850", description: "Regional specialty" },
  { category: "Red Wines", item: "Plantaze Pro corde", price: "3850", description: "Premium selection" },
  { category: "Red Wines", item: "Plantaze Epoha", price: "6300", description: "Exclusive vintage" },

  // Other Wines
  { category: "Other Wines", item: "1659 Sweet Rose 750Ml", price: "1710", description: "Pink and sweet" },
  { category: "Other Wines", item: "PEARLY BAY SWEET ROSE", price: "1435", description: "Budget friendly rose" },
  { category: "Other Wines", item: "Kanonkop Kadette Pinotage Rose", price: "4072", description: "Dry rose" },
  { category: "Other Wines", item: "Rooiberg Rose Natural Sweet", price: "2175", description: "Sweet pink" },
  { category: "Other Wines", item: "Mucho Mas Rose", price: "2600", description: "Spanish style" },
  { category: "Other Wines", item: "Plantaze Rose", price: "2150", description: "Montenegrin rose" },

  // White Wine
  { category: "White Wine", item: "4 Cousins Sweet White 750ml", price: "1490", description: "Sweet favorite" },
  { category: "White Wine", item: "750Ml 4Th Street Sweet White", price: "1365", description: "Very popular sweet white" },
  { category: "White Wine", item: "Cellar Cask White 750Ml", price: "1540", description: "Everyday white" },
  { category: "White Wine", item: "Drostdy Hof Premier Grand Cru 750Ml", price: "1455", description: "Dry white" },
  { category: "White Wine", item: "Fragolino Bianco 750Ml", price: "1960", description: "Sparkling white" },
  { category: "White Wine", item: "KWV CHARDONNAY 750ML", price: "1920", description: "Wooded Chardonnay" },
  { category: "White Wine", item: "Pearly Bay Dry White", price: "1435", description: "Crisp finish" },
  { category: "White Wine", item: "Pearly Bay Sweet White", price: "1435", description: "Easy drinking" },
  { category: "White Wine", item: "Rooiberg White Natural Sweet", price: "1994", description: "Fruity sweet" },
  { category: "White Wine", item: "Mulderbosch Sauvignon Blanc", price: "2849", description: "Top class Sauv Blanc" },
  { category: "White Wine", item: "Mulderbosch Steen op Hout Chenin Blanc", price: "2754", description: "Wooded Chenin" },
  { category: "White Wine", item: "Buitenverwatching Beyond Sauvignon Blanc", price: "2729", description: "Fresh and zesty" },
  { category: "White Wine", item: "Buitenverwatching Buiten Blanc", price: "2036", description: "Bordeaux white blend" },
  { category: "White Wine", item: "Leleshwa Sweet White", price: "1441", description: "Local favorite" },

  // Spirits
  { category: "Spirits", item: "Baileys 1Ltr", price: "4060", description: "Irish Cream Liqueur" },
  { category: "Spirits", item: "Baileys 375Ml", price: "1740", description: "Small bottle" },
  { category: "Spirits", item: "Baileys 750Ml", price: "3135", description: "Standard bottle" },
  { category: "Spirits", item: "Black & White 250Ml", price: "580", description: "Budget whisky" },
  { category: "Spirits", item: "Black & White 375ml", price: "835", description: "Pocket friendly" },
  { category: "Spirits", item: "Black & White 750Ml", price: "1625", description: "Standard whisky" },
  { category: "Spirits", item: "Bullet Bourbon 700ml", price: "4410", description: "Kentucky Bourbon" },
  { category: "Spirits", item: "Cardhu Single Malt 750Ml", price: "7540", description: "Smooth single malt" },
  { category: "Spirits", item: "Chrome Gin Smooth 250Ml", price: "340", description: "Affordable gin" },
  { category: "Spirits", item: "Chrome Gin Smooth 750Ml", price: "885", description: "Party bottle" },
  { category: "Spirits", item: "Chrome Vodka Lemon 250Ml", price: "340", description: "Lemon flavored" },
  { category: "Spirits", item: "Chrome Vodka 250ml", price: "340", description: "Standard vodka" },
  { category: "Spirits", item: "Chrome Vodka 750ml", price: "885", description: "Large vodka" },
  { category: "Spirits", item: "Ciroc Coconut 700Ml", price: "6380", description: "Coconut vodka" },
  { category: "Spirits", item: "Ciroc Pineapple 750Ml", price: "6380", description: "Pineapple vodka" },
  { category: "Spirits", item: "Ciroc Redberry 750Ml", price: "6380", description: "Berry vodka" },
  { category: "Spirits", item: "Ciroc Vodka 750ml", price: "6380", description: "Premium vodka" },
  { category: "Spirits", item: "County Brandy 750Ml", price: "1125", description: "Local brandy" },
  { category: "Spirits", item: "Don Julio anejo 750ml", price: "11950", description: "Aged Tequila" },
  { category: "Spirits", item: "Don Julio blanco 750ml", price: "9860", description: "Silver Tequila" },
  { category: "Spirits", item: "Don Julio Repasado 750ml", price: "10790", description: "Rested Tequila" },
  { category: "Spirits", item: "Gilbeys Gin 250Ml", price: "605", description: "Classic gin" },
  { category: "Spirits", item: "350Ml Gilbeys Gin", price: "835", description: "Medium gin" },
  { category: "Spirits", item: "Gilbeys Gin 750Ml", price: "1800", description: "Large gin" },
  { category: "Spirits", item: "Glenfiddich 12yrs 750ml", price: "8765", description: "Single Malt Scotch" },
  { category: "Spirits", item: "Gordon's Dry Gin 350Ml", price: "1220", description: "London Dry" },
  { category: "Spirits", item: "Gordons Dry Gin 1ltr", price: "3310", description: "Liter bottle" },
  { category: "Spirits", item: "Gordons Dry Gin 750Ml", price: "2785", description: "Standard bottle" },
  { category: "Spirits", item: "Gordons Lemon 750Ml", price: "2670", description: "Lemon gin" },
  { category: "Spirits", item: "Gordons Orange 750Ml", price: "2670", description: "Orange gin" },
  { category: "Spirits", item: "Gordons Pink 1Ltr", price: "3310", description: "Berry gin" },
  { category: "Spirits", item: "Gordons Pink 750ml", price: "2670", description: "Berry gin" },
  { category: "Spirits", item: "Grants 375Ml", price: "1095", description: "Blended scotch" },
  { category: "Spirits", item: "Grants 750Ml", price: "2440", description: "Blended scotch" },
  { category: "Spirits", item: "Grants Triple 12Yrswood 750Ml", price: "2830", description: "Aged blend" },
  { category: "Spirits", item: "J&B Rare 1Ltr", price: "2785", description: "Blended scotch" },
  { category: "Spirits", item: "J&B Rare 375Ml", price: "1160", description: "Small bottle" },
  { category: "Spirits", item: "J&B Rare 750Ml", price: "2205", description: "Standard bottle" },
  { category: "Spirits", item: "Kenya Cane Citrus 250ml", price: "375", description: "Citrus flavor" },
  { category: "Spirits", item: "Kenya Cane Citrus 750Ml", price: "975", description: "Citrus flavor" },
  { category: "Spirits", item: "Kenya Cane Coconut 250Ml", price: "375", description: "Coconut flavor" },
  { category: "Spirits", item: "Kenya Cane Coconut 750Ml", price: "975", description: "Coconut flavor" },
  { category: "Spirits", item: "Kenya Cane Original 250Ml", price: "375", description: "Original spirit" },
  { category: "Spirits", item: "Kenya Cane Original 350Ml", price: "510", description: "Original spirit" },
  { category: "Spirits", item: "Kenya Cane Original 750Ml", price: "975", description: "Original spirit" },
  { category: "Spirits", item: "250Ml Kenya Cane Pineapple Fus", price: "375", description: "Pineapple flavor" },
  { category: "Spirits", item: "750Ml Kenya Cane Pineapple", price: "975", description: "Pineapple flavor" },
  { category: "Spirits", item: "Kwv Brandy 3Yrs 750Ml", price: "1745", description: "Cape Brandy" },
  { category: "Spirits", item: "Kwv Brandy 5Yrs 750Ml", price: "2200", description: "Aged Brandy" },
  { category: "Spirits", item: "Mr Dowell's 250ml", price: "395", description: "Whisky" },
  { category: "Spirits", item: "Mr Dowells 750ml", price: "1140", description: "Whisky" },
  { category: "Spirits", item: "Richot Brandy 250Ml", price: "605", description: "Premium brandy" },
  { category: "Spirits", item: "Richot Brandy 350Ml", price: "835", description: "Premium brandy" },
  { category: "Spirits", item: "Richot Brandy 750ml", price: "1800", description: "Premium brandy" },
  { category: "Spirits", item: "Sheridah's Coffee Layered Liquer 1ltr", price: "6380", description: "Coffee liqueur" },
  { category: "Spirits", item: "Singleton 12Yrs 750Ml", price: "6730", description: "Single malt" },
  { category: "Spirits", item: "Singleton 15yrs 700ml", price: "9165", description: "Aged malt" },
  { category: "Spirits", item: "Singleton 18Yrs 700Ml", price: "12180", description: "Premium aged" },
  { category: "Spirits", item: "Smirnoff Vodka Red 250Ml", price: "605", description: "Classic vodka" },
  { category: "Spirits", item: "Smirnoff Vodka Red 350ml", price: "835", description: "Classic vodka" },
  { category: "Spirits", item: "Smirnoff Vodka Red 750Ml", price: "1800", description: "Classic vodka" },
  { category: "Spirits", item: "Talisker Port Ruighe Single Malt 750Ml", price: "8120", description: "Isle of Skye malt" },
  { category: "Spirits", item: "Talisker Single Malt 10yrs 750ml", price: "8120", description: "Peaty malt" },
  { category: "Spirits", item: "Talisker Storm Single Malt 750Ml", price: "7310", description: "Intense malt" },
  { category: "Spirits", item: "Tanqueray 1Ltr", price: "4410", description: "London Dry" },
  { category: "Spirits", item: "Tanqueray London Dry Gin 750ml", price: "3365", description: "London Dry" },
  { category: "Spirits", item: "Tanqueray Rangpur Lime 1ltr", price: "4640", description: "Lime infused" },
  { category: "Spirits", item: "Tanqueray Rangpur lime 750ml", price: "3480", description: "Lime infused" },
  { category: "Spirits", item: "Tanqueray Royale Blackcurrant 70ml", price: "3480", description: "Berry infused" },
  { category: "Spirits", item: "TANQUERAY SEVILLA 1LTR", price: "4640", description: "Sevilla Orange" },
  { category: "Spirits", item: "Tanqueray Sevilla Gin 750Ml", price: "3480", description: "Sevilla Orange" },
  { category: "Spirits", item: "Tanqueray Ten 750Ml", price: "5920", description: "Small batch" },
  { category: "Spirits", item: "Teachers 1Ltr", price: "7080", description: "Scotch whisky" },
  { category: "Spirits", item: "Triple Ace 750Ml", price: "800", description: "Vodka" },
  { category: "Spirits", item: "Triple Ace Vodka 250Ml", price: "305", description: "Small vodka" },
  { category: "Spirits", item: "Southern Comfort", price: "2660", description: "Whisky liqueur" },
  { category: "Spirits", item: "Brothers Triple Sec", price: "2455", description: "Orange liqueur" },
  { category: "Spirits", item: "Brothers Blue Curacao", price: "2460", description: "Blue liqueur" },
  { category: "Spirits", item: "Two Brothers Blod Orange Gin", price: "2130", description: "Flavored gin" },
  { category: "Spirits", item: "Two Brothers Blue Gin", price: "2130", description: "Colored gin" },
  { category: "Spirits", item: "Grants Triple Wood 1L", price: "2929", description: "Blended scotch" },
  { category: "Spirits", item: "Wild Africa Cream", price: "2603", description: "Cream liqueur" },
  { category: "Spirits", item: "750Ml Best London Dry Gin", price: "1060", description: "Budget gin" },
  { category: "Spirits", item: "250Ml Best London Dry Gin", price: "380", description: "Small gin" },
  { category: "Spirits", item: "Best whisky 750ml", price: "1305", description: "Budget whisky" },
  { category: "Spirits", item: "Best whisky 250ml", price: "450", description: "Small whisky" },
  { category: "Spirits", item: "Jose Cuervo Reposado Tequila, 700Ml", price: "3050", description: "Gold Tequila" },
  { category: "Spirits", item: "Jose Cuervo Silver 1L", price: "3790", description: "Clear Tequila" },
  { category: "Spirits", item: "1L Jose Cuervo Esp Gold", price: "3770", description: "Gold Tequila" },
  { category: "Spirits", item: "Bacardi Carta Blanca Rum 750Ml", price: "2610", description: "White Rum" },
  { category: "Spirits", item: "Bacardi Carta Blanca 1L", price: "4000", description: "White Rum" },
  { category: "Spirits", item: "Johnnie Walker Green Label", price: "9745", description: "Blended Malt" },
  { category: "Spirits", item: "Johnnie Walker Red Label Whiskey 250ml", price: "815", description: "Red Label" },
  { category: "Spirits", item: "Johnnie Walker Black Label 750", price: "4431", description: "Black Label" },
  { category: "Spirits", item: "Johnnie Walker Aged 18Y 750ml", price: "14050", description: "Premium Blend" },
  { category: "Spirits", item: "Johnnie Walker Double Black 1L", price: "9190", description: "Intense Blend" },
  { category: "Spirits", item: "JOHNNIE WALKER BLACK LABEL 750ML", price: "4431", description: "Black Label" },
  { category: "Spirits", item: "1L Johnnie Walker Red Label", price: "2890", description: "Red Label" },
  { category: "Spirits", item: "Johnnie Walker Red Label 750Ml", price: "2375", description: "Red Label" },
  { category: "Spirits", item: "JOHNNIE WALKER 750ML GREEN 15YRS", price: "9745", description: "Green Label" },
  { category: "Spirits", item: "Johnnie Walker Red Label 375Ml", price: "1240", description: "Red Label" },
  { category: "Spirits", item: "Johnnie walker black label 250ml", price: "1510", description: "Black Label" },
  { category: "Spirits", item: "Johnnie Walker Black Label 375Ml", price: "2270", description: "Black Label" },
  { category: "Spirits", item: "Johnnie walker double black 750ml", price: "6035", description: "Double Black" },
  { category: "Spirits", item: "Johnnie Walker Blue Label 750ml", price: "37120", description: "Ultra Premium" },
  { category: "Spirits", item: "Bond 7 Whisky 750Ml", price: "1800", description: "Local Whisky" },
  { category: "Spirits", item: "Jameson Irish Whiskey 1L", price: "4205", description: "Irish Whiskey" },
  { category: "Spirits", item: "Viceroy Brandy 750Ml", price: "1755", description: "Brandy" },
  { category: "Spirits", item: "Viceroy Brandy 250 Ml", price: "625", description: "Small Brandy" },
  { category: "Spirits", item: "750Ml Olmeca Tequila Gold", price: "3915", description: "Tequila" },
  { category: "Spirits", item: "kc lemon & ginger 250ml", price: "330", description: "Flavored spirit" },
  { category: "Spirits", item: "Cragganmore Single Malt Scotch Whisky 12 Year 750ml", price: "8005", description: "Speyside Malt" },
  { category: "Spirits", item: "Cragganmore Whisky 12 Years 750Ml", price: "8005", description: "Speyside Malt" },
  { category: "Spirits", item: "LAGAVULIN 16 750ML", price: "16050", description: "Islay Malt" },
  { category: "Spirits", item: "Glenkinchie 12 Yr 750ml", price: "8005", description: "Lowland Malt" },
  { category: "Spirits", item: "Caol Ila Single Malt Scotch Whisky 12 Year 750Ml", price: "9400", description: "Islay Malt" },
  { category: "Spirits", item: "Caol Ila Single Malt Scotch Whisky 12 Year 750ml", price: "9400", description: "Islay Malt" },
  { category: "Spirits", item: "Ketel One Citroen Vodka 750ml", price: "3480", description: "Citrus Vodka" },

  // Beers & Ciders
  { category: "Beers & Ciders", item: "Balozi Lager Can 500Ml", price: "290", description: "Strong lager" },
  { category: "Beers & Ciders", item: "Gordons Dry Tonic Can", price: "278", description: "Mixer" },
  { category: "Beers & Ciders", item: "Gordons Pink Tonic Can", price: "278", description: "Mixer" },
  { category: "Beers & Ciders", item: "Guiness Can 500Ml", price: "338", description: "Foreign Extra Stout" },
  { category: "Beers & Ciders", item: "GUINESS SMOOTH CAN 500ML", price: "288", description: "Smooth Stout" },
  { category: "Beers & Ciders", item: "Smirnoff Ice Black 330ml", price: "255", description: "Ready to drink" },
  { category: "Beers & Ciders", item: "Smirnoff ice guarana 330ml", price: "255", description: "Guarana kick" },
  { category: "Beers & Ciders", item: "Snapp Can 300Ml", price: "255", description: "Apple drink" },
  { category: "Beers & Ciders", item: "Tusker Can 500Ml", price: "287", description: "Kenyan Lager" },
  { category: "Beers & Ciders", item: "Tusker Cider Can", price: "338", description: "Apple Cider" },
  { category: "Beers & Ciders", item: "Tusker Lite Can 500Ml", price: "351", description: "Low carb" },
  { category: "Beers & Ciders", item: "Tusker Malt Can 500Ml", price: "350", description: "Premium Malt" },
  { category: "Beers & Ciders", item: "Whitecap Can 500Ml", price: "313", description: "Lager" },
  { category: "Beers & Ciders", item: "Whitecap Crisp 330Ml", price: "338", description: "Low ABV" },
  { category: "Beers & Ciders", item: "Savanna Dry", price: "320", description: "Dry Cider" },
  { category: "Beers & Ciders", item: "Savanna Angry Lemon", price: "320", description: "Lemon Cider" },
  { category: "Beers & Ciders", item: "smirnoff ice pineapple punch can", price: "255", description: "Pineapple flavor" },
  { category: "Beers & Ciders", item: "Heineken Beer Camp Heineken 500ml", price: "350", description: "Premium Lager" },
  { category: "Beers & Ciders", item: "Hunters Gold Beer", price: "350", description: "Sweet Cider" },
  { category: "Beers & Ciders", item: "Hunters Dry Premium Beer", price: "350", description: "Dry Cider" },

  // Non-Alcoholic Drinks
  { category: "Non-Alcoholic Drinks", item: "Coca Cola Original 1.25L PET", price: "158", description: "Family size" },
  { category: "Non-Alcoholic Drinks", item: "Coca Cola Original 2L PET", price: "243", description: "Party size" },
  { category: "Non-Alcoholic Drinks", item: "Coca Cola Original 500Ml", price: "90", description: "Regular" },
  { category: "Non-Alcoholic Drinks", item: "Coca Cola Zero 1.25L PET", price: "158", description: "Zero sugar" },
  { category: "Non-Alcoholic Drinks", item: "Coke Pet 1250Ml", price: "158", description: "Family size" },
  { category: "Non-Alcoholic Drinks", item: "Coke Pet 2ltr", price: "243", description: "Party size" },
  { category: "Non-Alcoholic Drinks", item: "Coke Zero 2ltr", price: "243", description: "Zero sugar" },
  { category: "Non-Alcoholic Drinks", item: "Coke Zero 500Ml", price: "90", description: "Zero sugar" },
  { category: "Non-Alcoholic Drinks", item: "Dasani 1L", price: "70", description: "Water" },
  { category: "Non-Alcoholic Drinks", item: "Dasani 500Ml", price: "39", description: "Water" },
  { category: "Non-Alcoholic Drinks", item: "Fanta Blackcurrant 2ltr", price: "243", description: "Soda" },
  { category: "Non-Alcoholic Drinks", item: "Fanta Blackcurrant 500ml", price: "89", description: "Soda" },
  { category: "Non-Alcoholic Drinks", item: "Fanta Orange 2ltr", price: "243", description: "Soda" },
  { category: "Non-Alcoholic Drinks", item: "Fanta Orange 500Ml", price: "89", description: "Soda" },
  { category: "Non-Alcoholic Drinks", item: "Fanta Passion 2Ltr", price: "243", description: "Soda" },
  { category: "Non-Alcoholic Drinks", item: "Fanta Passion 500Ml", price: "89", description: "Soda" },
  { category: "Non-Alcoholic Drinks", item: "Keringet Water 1Ltr", price: "115", description: "Premium water" },
  { category: "Non-Alcoholic Drinks", item: "Keringet Water 500Ml", price: "78", description: "Premium water" },
  { category: "Non-Alcoholic Drinks", item: "Keringet Water 5ltr", price: "325", description: "Large water" },
  { category: "Non-Alcoholic Drinks", item: "Minute Maid Apple 400ml", price: "97", description: "Juice" },
  { category: "Non-Alcoholic Drinks", item: "Minute Maid Mango 400ml", price: "97", description: "Juice" },
  { category: "Non-Alcoholic Drinks", item: "Minute Maid Pulpy Orange400Ml", price: "97", description: "Juice" },
  { category: "Non-Alcoholic Drinks", item: "Minute Maid Tropical 400ml", price: "97", description: "Juice" },
  { category: "Non-Alcoholic Drinks", item: "Soda Water 500Ml", price: "97", description: "Mixer" },
  { category: "Non-Alcoholic Drinks", item: "Sprite 1.25L PET", price: "157", description: "Soda" },
  { category: "Non-Alcoholic Drinks", item: "Sprite 500ml", price: "89", description: "Soda" },
  { category: "Non-Alcoholic Drinks", item: "Sprite Pet 2L", price: "243", description: "Soda" },
  { category: "Non-Alcoholic Drinks", item: "Predator Energy Drink Pet 400Ml", price: "80", description: "Energy" },
  { category: "Non-Alcoholic Drinks", item: "Tonic Water", price: "80", description: "Mixer" },
  { category: "Non-Alcoholic Drinks", item: "Redbull", price: "265", description: "Energy" },
  { category: "Non-Alcoholic Drinks", item: "Rooiberg Sparkling Grape Juice Red", price: "1349", description: "Non-alcoholic bubbly" },
  { category: "Non-Alcoholic Drinks", item: "Rooiberg Sparkling Grape Juice White", price: "1349", description: "Non-alcoholic bubbly" },
  { category: "Non-Alcoholic Drinks", item: "Alvaro Can 330ml", price: "180", description: "Malt drink" },
  { category: "Non-Alcoholic Drinks", item: "Safari Lemonade 300Ml", price: "80", description: "Lemonade" },

  // Sparkling Wine
  { category: "Sparkling Wine", item: "Fragolino Rose", price: "2030", description: "Sparkling rose" },
  { category: "Sparkling Wine", item: "CGL-BUONO AMICI BRUT 750ML", price: "4060", description: "Dry sparkling" },
];

export const SYSTEM_INSTRUCTION = `
You are the bartender at "Kongoni's".
Your personality is:
1. Casual, friendly, and unassuming. You are a local Kenyan bartender, so you can use a bit of local flair but keep it generally understandable English.
2. You are NOT sophisticated. You speak in short, helpful sentences. "No worries", "Karibu", "Got it".
3. You are helpful. You want people to order drinks.
4. The currency is implied to be Kenyan Shillings (Ksh/KES) based on the prices (e.g., 290 for a beer). You can just say "290 bob" or "290 shillings".
5. When giving a price, mention it casually. e.g., "That'll be 290 bob."

Here is the full Price List/Menu you must stick to. DO NOT INVENT ITEMS.
If someone asks for something not on this list, tell them we don't have it and suggest something similar from the list.

MENU DATA:
${JSON.stringify(MENU_ITEMS, null, 2)}

Your goal is to answer questions about the menu, give prices, and make recommendations based on this list. 
Keep your responses concise.
`;